version: "3.8"

services:
  mariadb:
    image: mariadb:10.9
    container_name: wis4_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wis4_db
      MYSQL_USER: wis4_user
      MYSQL_PASSWORD: wis4_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d   # garante que a pasta existe no repo
    ports:
      - "3306:3306"
    networks: [wis4_network]

  s3ninja:
    image: scireum/s3-ninja
    container_name: wis4_s3ninja
    ports:
      - "9000:9000"
    volumes:
      - s3_data:/home/sirius/data
    networks: [wis4_network]

  backend:
    build: ./backend
    image: wis4pro-backend:latest
    container_name: wis4_backend
    depends_on: [mariadb, s3ninja]
    networks: [wis4_network]
    environment:
      DB_HOST: mariadb
      DB_USER: wis4_user
      DB_PASS: wis4_password
      DB_NAME: wis4_db
      S3_ENDPOINT: http://s3ninja:9000
      S3_PUBLIC_ENDPOINT: http://localhost:9000
      S3_BUCKET: wis4-documents
      S3_REGION: us-east-1
      S3_KEY: AKIAIOSFODNN7EXAMPLE
      S3_SECRET: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      S3_USE_PATH_STYLE: "true"

  frontend:
    build: ./frontend
    image: wis4pro-frontend:latest
    container_name: wis4_frontend
    networks: [wis4_network]

  nginx:
    build: ./nginx
    image: wis4-nginx:latest
    container_name: wis4_nginx
    ports:
      - "80:80"
    depends_on: [backend, frontend]
    networks: [wis4_network]

volumes:
  mariadb_data:
  s3_data:

networks:
  wis4_network:
    driver: bridge
